In [77]:
"""ML"""
import torch
import torch.nn.functional as F
import numpy as np

"""Visualization"""
from matplotlib import pyplot as plt

"""Dataset and Preprocessing"""
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

"""Utils"""
# Add Base directory to Python path
import sys
import os
from pathlib import Path
sys.path.append(str(Path().resolve().parent))
from Utils.paths import *
import Utils.plotting as plotting
import Utils.json_inter as json_inter 
from Assets.Models.Models import *

from tqdm import tqdm

"""Logger"""
from Logger import *
logger = Logger(f"{LOGS}\\training.log", f"{LOGS}\\.sesh")

torch.manual_seed(0)
np.random.seed(0)

%load_ext autoreload
%autoreload 2

torch.__version__, np.__version__

Logger initialized with file D:\Repos\FPGA_Radar_Microdoppler_Classification\Logs\training.log, default tag [DEF] and level [INFO]
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

('2.5.1+cu118', '2.0.1')

In [78]:
json_inter.load_config_as_dataframe("preprocess_metadata.json")

,run_id,window_size,stride,snr_threshold,test_size,val_size,random_seed,balance_classes,dataset_name,file_name,timestamp,doppler_bins,correlation_threshold,max_lag,size,file_path
0,open_radar_K128_S32_SNR3.0_002,128,32,3.0,0.2,0.1,42,True,open_radar,open_radar_K128_S32_SNR3.npz,2026-02-23 13:45:53,,,,,
1,open_radar_K64_S32_SNR3.0_003,64,32,3.0,0.2,0.1,42,True,open_radar,open_radar_K64_S32_SNR3.npz,2026-02-23 13:54:47,,,,,
2,open_radar_K256_S32_SNR3.0_004,256,32,3.0,0.2,0.1,42,True,open_radar,open_radar_K256_S32_SNR3.npz,2026-02-23 13:58:14,1008.0,,,,
3,004,128,42,,0.1,0.1,42,,radar_windows_corr_stride,dataset,2026-02-24 19:50:38,1008.0,0.25,512.0,4.60 GB,
4,005,128,42,,0.1,0.1,0,,radar_windows_corr_stride,dataset,2026-02-24 20:17:44,1008.0,0.25,512.0,1.499 GB,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...
5,006,64,42,,0.1,0.1,0,,radar_windows_corr_stride,dataset,2026-02-24 21:25:22,1008.0,0.25,512.0,0.8329 GB,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...
6,007,32,32,,0.1,0.1,0,,radar_windows_corr_stride,dataset,2026-02-24 21:40:52,1008.0,0.25,512.0,0.576 GB,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...
7,008,32,16,,0.1,0.1,0,,radar_windows_corr_stride,dataset,2026-02-24 21:44:38,1008.0,0.25,512.0,1.1336 GB,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...
8,009,32,16,,0.1,0.1,0,,radar_windows_corr_stride,dataset,2026-02-24 22:41:20,256.0,0.25,512.0,0.1485 GB,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...
9,010,32,16,,0.1,0.1,0,,radar_windows_corr_stride,dataset,2026-02-25 00:33:02,256.0,0.25,512.0,0.1485 GB,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...
10,011,32,32,,0.1,0.1,0,,radar_windows_corr_stride,dataset,2026-02-25 00:33:58,256.0,0.25,512.0,0.1445 GB,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...
11,012,32,16,,0.1,0.1,0,,radar_windows_corr_stride,dataset,2026-02-25 00:37:19,512.0,0.25,512.0,0.5766 GB,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...

In [79]:
# # def load_processed_dataset(path,
# #                            to_torch=False,
# #                            device="cpu",
# #                            return_config=True,
# #                            verbose=True):
# #     """
# #     Loads radar window dataset and encodes string labels.
# #     """

# #     data = np.load(path, allow_pickle=True)

# #     train_X = data["train_X"]
# #     train_y = data["train_y"]
# #     val_X   = data["val_X"]
# #     val_y   = data["val_y"]
# #     test_X  = data["test_X"]
# #     test_y  = data["test_y"]

# #     config = data["config"].item() if "config" in data else None

# #     # -------------------------------------------------
# #     # 🔹 Encode string labels if necessary
# #     # -------------------------------------------------
# #     if train_y.dtype.type is np.str_ or train_y.dtype == object:

# #         all_labels = np.concatenate([train_y, val_y, test_y])
# #         classes = sorted(np.unique(all_labels))

# #         class_to_idx = {cls: i for i, cls in enumerate(classes)}
# #         idx_to_class = {i: cls for cls, i in class_to_idx.items()}

# #         train_y = np.array([class_to_idx[y] for y in train_y])
# #         val_y   = np.array([class_to_idx[y] for y in val_y])
# #         test_y  = np.array([class_to_idx[y] for y in test_y])

# #     else:
# #         class_to_idx = None
# #         idx_to_class = None

# #     # -------------------------------------------------
# #     # Convert to torch if requested
# #     # -------------------------------------------------
# #     if to_torch:
# #         train_X = torch.tensor(train_X, dtype=torch.float32, device=device)
# #         val_X   = torch.tensor(val_X, dtype=torch.float32, device=device)
# #         test_X  = torch.tensor(test_X, dtype=torch.float32, device=device)

# #         train_y = torch.tensor(train_y, dtype=torch.long, device=device)
# #         val_y   = torch.tensor(val_y, dtype=torch.long, device=device)
# #         test_y  = torch.tensor(test_y, dtype=torch.long, device=device)

# #     if verbose:
# #         print("="*50)
# #         print(f"Loaded: {path}")
# #         print("-"*50)
# #         print(f"Train: {train_X.shape}")
# #         print(f"Val  : {val_X.shape}")
# #         print(f"Test : {test_X.shape}")
# #         print(f"Num classes: {len(class_to_idx) if class_to_idx else 'Unknown'}")
# #         print("="*50)

# #     result = {
# #         "train_X": train_X,
# #         "train_y": train_y,
# #         "val_X": val_X,
# #         "val_y": val_y,
# #         "test_X": test_X,
# #         "test_y": test_y,
# #         "class_to_idx": class_to_idx,
# #         "idx_to_class": idx_to_class
# #     }

# #     if return_config:
# #         result["config"] = config

# #     return result
# # dataset_path = PATHS['PROCESSED_DATASETS'] +"\\"+ "open_radar_K64_S32_SNR3.0.npz"	
# # dataset = load_processed_dataset(
# #     dataset_path,
# #     to_torch=True,
# #     device="cuda"
# # )

# # train_X = dataset["train_X"]
# # train_y = dataset["train_y"]
# from collections import Counter

# def print_class_counts(dataset, name):
#     counts = Counter([item["label"] for item in dataset])
#     print(f"\n{name} distribution:")
#     for k, v in counts.items():
#         print(f"{k}: {v}")
#     print(f"Total: {sum(counts.values())}")

# print_class_counts(train_data, "Train (before balance)")
# print_class_counts(val_data, "Val (before balance)")
# print_class_counts(test_data, "Test (before balance)")

In [80]:
CONFIG = json_inter.read_json_config("model.config")

DATA_CONFIG = json_inter.get_config_by_id(LOGS+"\\"+"preprocess_metadata.json", CONFIG["dataset_id"])


CONFIG
DATA_CONFIG

CONFIG['dataset_path'] = DATA_CONFIG['file_path']
CONFIG['model_save_path'] = OUTPUTS + "\\" + "Models"
CONFIG, DATA_CONFIG

({'dataset_id': '012',
  'batch_size': 64,
  'epochs': 100,
  'learning_rate': 0.001,
  'use_class_weights': True,
  'model_name': 'cnn001',
  'dataset_path': 'D:\\Repos\\FPGA_Radar_Microdoppler_Classification\\Assets\\Dataset\\Processed\\radar_windows_corr_stride_K32_S16_DB512.npz',
  'model_save_path': 'D:\\Repos\\FPGA_Radar_Microdoppler_Classification\\Outputs\\Models'},
 {'window_size': 32,
  'stride': 16,
  'correlation_threshold': 0.25,
  'doppler_bins': 512,
  'max_lag': 512,
  'test_size': 0.1,
  'val_size': 0.1,
  'random_seed': 0,
  'dataset_name': 'radar_windows_corr_stride',
  'file_name': 'dataset',
  'file_path': 'D:\\Repos\\FPGA_Radar_Microdoppler_Classification\\Assets\\Dataset\\Processed\\radar_windows_corr_stride_K32_S16_DB512.npz',
  'timestamp': '2026-02-25 00:37:19',
  'size': '0.5766 GB'})

In [ ]:
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import os


class RadarDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]




def train_model(train_data, val_data, test_data):

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    train_dataset = RadarDataset(*train_data)
    val_dataset   = RadarDataset(*val_data)
    test_dataset  = RadarDataset(*test_data)

    train_loader = DataLoader(train_dataset,
                              batch_size=CONFIG["batch_size"],
                              shuffle=True)

    val_loader = DataLoader(val_dataset,
                            batch_size=CONFIG["batch_size"],
                            shuffle=False)

    test_loader = DataLoader(test_dataset,
                             batch_size=CONFIG["batch_size"],
                             shuffle=False)

    input_height = train_data[0].shape[2]
    input_width  = train_data[0].shape[3]
    num_classes  = CONFIG["num_classes"]

    model = BasicRadarCNN(input_height, input_width, num_classes).to(device)

    # Optional class weighting
    if CONFIG.get("use_class_weights", False):
        class_counts = np.bincount(train_data[1])
        weights = 1.0 / (class_counts + 1e-8)
        weights = weights / weights.sum() * len(class_counts)
        weights = torch.tensor(weights, dtype=torch.float32).to(device)
        criterion = nn.CrossEntropyLoss(weight=weights)
    else:
        criterion = nn.CrossEntropyLoss()

    optimizer = optim.Adam(model.parameters(), lr=CONFIG["learning_rate"])

    best_val_acc = 0.0

    logger("\nStarting Training...\n", tag=BEGIN)

    best_epoch = 0

    for epoch in range(CONFIG["epochs"]):

        model.train()
        train_loss = 0
        correct = 0
        total = 0

        for X, y in train_loader:
            X, y = X.to(device), y.to(device)

            optimizer.zero_grad()
            outputs = model(X)
            loss = criterion(outputs, y)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            _, predicted = outputs.max(1)
            total += y.size(0)
            correct += predicted.eq(y).sum().item()

        train_acc = correct / total


        model.eval()
        val_loss = 0
        correct = 0
        total = 0

        with torch.no_grad():
            for X, y in val_loader:
                X, y = X.to(device), y.to(device)
                outputs = model(X)
                loss = criterion(outputs, y)

                val_loss += loss.item()
                _, predicted = outputs.max(1)
                total += y.size(0)
                correct += predicted.eq(y).sum().item()

        val_acc = correct / total
        
        logger(f"Epoch [{epoch}/{CONFIG['epochs']}]")
        logger(f"Train ACC: {train_acc:.4f}")
        logger(f"Val ACC: {val_acc:.4f}")
        logger(f"Train Loss: {train_loss:.4f}")
        logger(f"Val Loss: {val_loss:.4f}")
        logger("="*30)
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_epoch = epoch
            torch.save(model.state_dict(),
                       os.path.join(CONFIG["model_save_path"],
                                    CONFIG["model_name"] + ".pt"))

    logger("\n\nTraining Complete.")
    logger(f"Best Val Accuracy: {best_val_acc}")
    logger(f"Best Epoch: {best_epoch}")

    model.load_state_dict(torch.load(
        os.path.join(CONFIG["model_save_path"],
                     CONFIG["model_name"] + ".pt")
    ))

    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for X, y in test_loader:
            X, y = X.to(device), y.to(device)
            outputs = model(X)
            _, predicted = outputs.max(1)
            total += y.size(0)
            correct += predicted.eq(y).sum().item()

    test_acc = correct / total
    logger(f"Test Accuracy: {test_acc}")
    
    return model

In [82]:
logger.start_session()


logger("="*60)
logger("Loading dataset...")
logger(DATA_CONFIG.__str__(), tag=META)
logger(CONFIG.__str__(), tag=META)
logger("="*60)

dataset_path = CONFIG["dataset_path"]

data = np.load(dataset_path, allow_pickle=True)

train_X = data["train_X"]
train_y = data["train_y"]
val_X   = data["val_X"]
val_y   = data["val_y"]
test_X  = data["test_X"]
test_y  = data["test_y"]

logger(f"Train: {str(train_X.shape)}", tag=META)
logger(f"Val  : {str(val_X.shape)}", tag=META)
logger(f"Test : {str(test_X.shape)}", tag=META)


num_classes = len(np.unique(train_y))
CONFIG["num_classes"] = num_classes

logger(f"Num Classes: {num_classes}", tag=META)
logger(f"="*60)


os.makedirs(CONFIG["model_save_path"], exist_ok=True)


model = train_model(
    (train_X, train_y),
    (val_X, val_y),
    (test_X, test_y)
)


logger("\nExecution Complete.", tag=FINISH)


json_inter.save_config_to_json(CONFIG, "experiments_metadata")


logger.end_session()

[2026-02-25 00:38:06] [INFO] [MET]: START Session 11
[2026-02-25 00:38:06] [INFO] [DEF]: ============================================================
[2026-02-25 00:38:06] [INFO] [DEF]: Loading dataset...
[2026-02-25 00:38:06] [INFO] [MET]: {'window_size': 32, 'stride': 16, 'correlation_threshold': 0.25, 'doppler_bins': 512, 'max_lag': 512, 'test_size': 0.1, 'val_size': 0.1, 'random_seed': 0, 'dataset_name': 'radar_windows_corr_stride', 'file_name': 'dataset', 'file_path': 'D:\\Repos\\FPGA_Radar_Microdoppler_Classification\\Assets\\Dataset\\Processed\\radar_windows_corr_stride_K32_S16_DB512.npz', 'timestamp': '2026-02-25 00:37:19', 'size': '0.5766 GB'}
[2026-02-25 00:38:06] [INFO] [DEF]: ============================================================
[2026-02-25 00:38:09] [INFO] [MET]: Train: (8931, 1, 32, 512)
[2026-02-25 00:38:09] [INFO] [MET]: Val  : (995, 1, 32, 512)
[2026-02-25 00:38:09] [INFO] [MET]: Test : (1272, 1, 32, 512)
[2026-02-25 00:38:09] [INFO] [MET]: Num Classes: 4
[2026-02-25 00:38:09] [INFO] [DEF]: ============================================================
[2026-02-25 00:38:09] [INFO] [BEG]: Starting Training...
[2026-02-25 00:38:13] [INFO] [DEF]: Epoch [1/100]
[2026-02-25 00:38:13] [INFO] [DEF]: Train Loss: 147.9454
[2026-02-25 00:38:13] [INFO] [DEF]: Train Acc: 0.6182
[2026-02-25 00:38:13] [INFO] [DEF]: Val Loss: 8.5446
[2026-02-25 00:38:13] [INFO] [DEF]: Val Acc: 0.8040
[2026-02-25 00:38:16] [INFO] [DEF]: Epoch [2/100]
[2026-02-25 00:38:16] [INFO] [DEF]: Train Loss: 86.0636
[2026-02-25 00:38:16] [INFO] [DEF]: Train Acc: 0.7343
[2026-02-25 00:38:16] [INFO] [DEF]: Val Loss: 8.3643
[2026-02-25 00:38:16] [INFO] [DEF]: Val Acc: 0.8040
[2026-02-25 00:38:19] [INFO] [DEF]: Epoch [3/100]
[2026-02-25 00:38:19] [INFO] [DEF]: Train Loss: 67.0399
[2026-02-25 00:38:19] [INFO] [DEF]: Train Acc: 0.7967
[2026-02-25 00:38:19] [INFO] [DEF]: Val Loss: 7.2842
[2026-02-25 00:38:19] [INFO] [DEF]: Val Acc: 0.8744
[2026-02-25 00:38:22] [INFO] [DEF]: Epoch [4/100]
[2026-02-25 00:38:22] [INFO] [DEF]: Train Loss: 58.8550
[2026-02-25 00:38:22] [INFO] [DEF]: Train Acc: 0.8240
[2026-02-25 00:38:22] [INFO] [DEF]: Val Loss: 30.6902
[2026-02-25 00:38:22] [INFO] [DEF]: Val Acc: 0.5307
[2026-02-25 00:38:25] [INFO] [DEF]: Epoch [5/100]
[2026-02-25 00:38:25] [INFO] [DEF]: Train Loss: 50.6598
[2026-02-25 00:38:25] [INFO] [DEF]: Train Acc: 0.8516
[2026-02-25 00:38:25] [INFO] [DEF]: Val Loss: 23.8047
[2026-02-25 00:38:25] [INFO] [DEF]: Val Acc: 0.6211
[2026-02-25 00:38:28] [INFO] [DEF]: Epoch [6/100]
[2026-02-25 00:38:28] [INFO] [DEF]: Train Loss: 47.6121
[2026-02-25 00:38:28] [INFO] [DEF]: Train Acc: 0.8633
[2026-02-25 00:38:28] [INFO] [DEF]: Val Loss: 12.5896
[2026-02-25 00:38:28] [INFO] [DEF]: Val Acc: 0.7980
[2026-02-25 00:38:31] [INFO] [DEF]: Epoch [7/100]
[2026-02-25 00:38:31] [INFO] [DEF]: Train Loss: 44.2742
[2026-02-25 00:38:31] [INFO] [DEF]: Train Acc: 0.8717
[2026-02-25 00:38:31] [INFO] [DEF]: Val Loss: 16.4063
[2026-02-25 00:38:31] [INFO] [DEF]: Val Acc: 0.6995
[2026-02-25 00:38:34] [INFO] [DEF]: Epoch [8/100]
[2026-02-25 00:38:34] [INFO] [DEF]: Train Loss: 39.0984
[2026-02-25 00:38:34] [INFO] [DEF]: Train Acc: 0.8813
[2026-02-25 00:38:34] [INFO] [DEF]: Val Loss: 11.9192
[2026-02-25 00:38:34] [INFO] [DEF]: Val Acc: 0.7638
[2026-02-25 00:38:36] [INFO] [DEF]: Epoch [9/100]
[2026-02-25 00:38:36] [INFO] [DEF]: Train Loss: 37.7229
[2026-02-25 00:38:36] [INFO] [DEF]: Train Acc: 0.8911
[2026-02-25 00:38:36] [INFO] [DEF]: Val Loss: 33.7395
[2026-02-25 00:38:36] [INFO] [DEF]: Val Acc: 0.5759
[2026-02-25 00:38:39] [INFO] [DEF]: Epoch [10/100]
[2026-02-25 00:38:39] [INFO] [DEF]: Train Loss: 34.2664
[2026-02-25 00:38:39] [INFO] [DEF]: Train Acc: 0.8978
[2026-02-25 00:38:39] [INFO] [DEF]: Val Loss: 44.9525
[2026-02-25 00:38:39] [INFO] [DEF]: Val Acc: 0.5266
[2026-02-25 00:38:43] [INFO] [DEF]: Epoch [11/100]
[2026-02-25 00:38:43] [INFO] [DEF]: Train Loss: 32.4185
[2026-02-25 00:38:43] [INFO] [DEF]: Train Acc: 0.9019
[2026-02-25 00:38:43] [INFO] [DEF]: Val Loss: 14.4742
[2026-02-25 00:38:43] [INFO] [DEF]: Val Acc: 0.7960
[2026-02-25 00:38:46] [INFO] [DEF]: Epoch [12/100]
[2026-02-25 00:38:46] [INFO] [DEF]: Train Loss: 29.4607
[2026-02-25 00:38:46] [INFO] [DEF]: Train Acc: 0.9159
[2026-02-25 00:38:46] [INFO] [DEF]: Val Loss: 61.2184
[2026-02-25 00:38:46] [INFO] [DEF]: Val Acc: 0.7980
[2026-02-25 00:38:49] [INFO] [DEF]: Epoch [13/100]
[2026-02-25 00:38:49] [INFO] [DEF]: Train Loss: 29.9571
[2026-02-25 00:38:49] [INFO] [DEF]: Train Acc: 0.9123
[2026-02-25 00:38:49] [INFO] [DEF]: Val Loss: 28.2662
[2026-02-25 00:38:49] [INFO] [DEF]: Val Acc: 0.8553
[2026-02-25 00:38:52] [INFO] [DEF]: Epoch [14/100]
[2026-02-25 00:38:52] [INFO] [DEF]: Train Loss: 28.8206
[2026-02-25 00:38:52] [INFO] [DEF]: Train Acc: 0.9182
[2026-02-25 00:38:52] [INFO] [DEF]: Val Loss: 49.8269
[2026-02-25 00:38:52] [INFO] [DEF]: Val Acc: 0.7166
[2026-02-25 00:38:55] [INFO] [DEF]: Epoch [15/100]
[2026-02-25 00:38:55] [INFO] [DEF]: Train Loss: 26.8143
[2026-02-25 00:38:55] [INFO] [DEF]: Train Acc: 0.9214
[2026-02-25 00:38:55] [INFO] [DEF]: Val Loss: 21.2666
[2026-02-25 00:38:55] [INFO] [DEF]: Val Acc: 0.7327
[2026-02-25 00:38:59] [INFO] [DEF]: Epoch [16/100]
[2026-02-25 00:38:59] [INFO] [DEF]: Train Loss: 26.5121
[2026-02-25 00:38:59] [INFO] [DEF]: Train Acc: 0.9205
[2026-02-25 00:38:59] [INFO] [DEF]: Val Loss: 12.0335
[2026-02-25 00:38:59] [INFO] [DEF]: Val Acc: 0.8171
[2026-02-25 00:39:02] [INFO] [DEF]: Epoch [17/100]
[2026-02-25 00:39:02] [INFO] [DEF]: Train Loss: 22.7914
[2026-02-25 00:39:02] [INFO] [DEF]: Train Acc: 0.9342
[2026-02-25 00:39:02] [INFO] [DEF]: Val Loss: 11.7517
[2026-02-25 00:39:02] [INFO] [DEF]: Val Acc: 0.8010
[2026-02-25 00:39:06] [INFO] [DEF]: Epoch [18/100]
[2026-02-25 00:39:06] [INFO] [DEF]: Train Loss: 21.8463
[2026-02-25 00:39:06] [INFO] [DEF]: Train Acc: 0.9342
[2026-02-25 00:39:06] [INFO] [DEF]: Val Loss: 57.7249
[2026-02-25 00:39:06] [INFO] [DEF]: Val Acc: 0.7739
[2026-02-25 00:39:10] [INFO] [DEF]: Epoch [19/100]
[2026-02-25 00:39:10] [INFO] [DEF]: Train Loss: 23.1339
[2026-02-25 00:39:10] [INFO] [DEF]: Train Acc: 0.9304
[2026-02-25 00:39:10] [INFO] [DEF]: Val Loss: 5.3740
[2026-02-25 00:39:10] [INFO] [DEF]: Val Acc: 0.9116
[2026-02-25 00:39:13] [INFO] [DEF]: Epoch [20/100]
[2026-02-25 00:39:13] [INFO] [DEF]: Train Loss: 20.6856
[2026-02-25 00:39:13] [INFO] [DEF]: Train Acc: 0.9399
[2026-02-25 00:39:13] [INFO] [DEF]: Val Loss: 19.3423
[2026-02-25 00:39:13] [INFO] [DEF]: Val Acc: 0.7548
[2026-02-25 00:39:17] [INFO] [DEF]: Epoch [21/100]
[2026-02-25 00:39:17] [INFO] [DEF]: Train Loss: 21.8373
[2026-02-25 00:39:17] [INFO] [DEF]: Train Acc: 0.9380
[2026-02-25 00:39:17] [INFO] [DEF]: Val Loss: 12.3556
[2026-02-25 00:39:17] [INFO] [DEF]: Val Acc: 0.8884
[2026-02-25 00:39:21] [INFO] [DEF]: Epoch [22/100]
[2026-02-25 00:39:21] [INFO] [DEF]: Train Loss: 18.7064
[2026-02-25 00:39:21] [INFO] [DEF]: Train Acc: 0.9457
[2026-02-25 00:39:21] [INFO] [DEF]: Val Loss: 6.6382
[2026-02-25 00:39:21] [INFO] [DEF]: Val Acc: 0.9578
[2026-02-25 00:39:25] [INFO] [DEF]: Epoch [23/100]
[2026-02-25 00:39:25] [INFO] [DEF]: Train Loss: 19.7793
[2026-02-25 00:39:25] [INFO] [DEF]: Train Acc: 0.9421
[2026-02-25 00:39:25] [INFO] [DEF]: Val Loss: 5.8128
[2026-02-25 00:39:25] [INFO] [DEF]: Val Acc: 0.9447
[2026-02-25 00:39:29] [INFO] [DEF]: Epoch [24/100]
[2026-02-25 00:39:29] [INFO] [DEF]: Train Loss: 17.4497
[2026-02-25 00:39:29] [INFO] [DEF]: Train Acc: 0.9496
[2026-02-25 00:39:29] [INFO] [DEF]: Val Loss: 15.6541
[2026-02-25 00:39:29] [INFO] [DEF]: Val Acc: 0.9055
[2026-02-25 00:39:33] [INFO] [DEF]: Epoch [25/100]
[2026-02-25 00:39:33] [INFO] [DEF]: Train Loss: 14.9708
[2026-02-25 00:39:33] [INFO] [DEF]: Train Acc: 0.9549
[2026-02-25 00:39:33] [INFO] [DEF]: Val Loss: 18.1590
[2026-02-25 00:39:33] [INFO] [DEF]: Val Acc: 0.7709
[2026-02-25 00:39:37] [INFO] [DEF]: Epoch [26/100]
[2026-02-25 00:39:37] [INFO] [DEF]: Train Loss: 16.3131
[2026-02-25 00:39:37] [INFO] [DEF]: Train Acc: 0.9501
[2026-02-25 00:39:37] [INFO] [DEF]: Val Loss: 25.0884
[2026-02-25 00:39:37] [INFO] [DEF]: Val Acc: 0.7698
[2026-02-25 00:39:41] [INFO] [DEF]: Epoch [27/100]
[2026-02-25 00:39:41] [INFO] [DEF]: Train Loss: 15.2576
[2026-02-25 00:39:41] [INFO] [DEF]: Train Acc: 0.9545
[2026-02-25 00:39:41] [INFO] [DEF]: Val Loss: 22.6982
[2026-02-25 00:39:41] [INFO] [DEF]: Val Acc: 0.8955
[2026-02-25 00:39:45] [INFO] [DEF]: Epoch [28/100]
[2026-02-25 00:39:45] [INFO] [DEF]: Train Loss: 15.7261
[2026-02-25 00:39:45] [INFO] [DEF]: Train Acc: 0.9543
[2026-02-25 00:39:45] [INFO] [DEF]: Val Loss: 4.2982
[2026-02-25 00:39:45] [INFO] [DEF]: Val Acc: 0.9548
[2026-02-25 00:39:49] [INFO] [DEF]: Epoch [29/100]
[2026-02-25 00:39:49] [INFO] [DEF]: Train Loss: 14.7875
[2026-02-25 00:39:49] [INFO] [DEF]: Train Acc: 0.9561
[2026-02-25 00:39:49] [INFO] [DEF]: Val Loss: 16.5069
[2026-02-25 00:39:49] [INFO] [DEF]: Val Acc: 0.8211
[2026-02-25 00:39:53] [INFO] [DEF]: Epoch [30/100]
[2026-02-25 00:39:53] [INFO] [DEF]: Train Loss: 15.7845
[2026-02-25 00:39:53] [INFO] [DEF]: Train Acc: 0.9542
[2026-02-25 00:39:53] [INFO] [DEF]: Val Loss: 13.8751
[2026-02-25 00:39:53] [INFO] [DEF]: Val Acc: 0.8271
[2026-02-25 00:39:57] [INFO] [DEF]: Epoch [31/100]
[2026-02-25 00:39:57] [INFO] [DEF]: Train Loss: 12.5292
[2026-02-25 00:39:57] [INFO] [DEF]: Train Acc: 0.9641
[2026-02-25 00:39:57] [INFO] [DEF]: Val Loss: 21.9982
[2026-02-25 00:39:57] [INFO] [DEF]: Val Acc: 0.7869
[2026-02-25 00:40:02] [INFO] [DEF]: Epoch [32/100]
[2026-02-25 00:40:02] [INFO] [DEF]: Train Loss: 10.8156
[2026-02-25 00:40:02] [INFO] [DEF]: Train Acc: 0.9678
[2026-02-25 00:40:02] [INFO] [DEF]: Val Loss: 50.3084
[2026-02-25 00:40:02] [INFO] [DEF]: Val Acc: 0.7930
[2026-02-25 00:40:06] [INFO] [DEF]: Epoch [33/100]
[2026-02-25 00:40:06] [INFO] [DEF]: Train Loss: 12.9804
[2026-02-25 00:40:06] [INFO] [DEF]: Train Acc: 0.9633
[2026-02-25 00:40:06] [INFO] [DEF]: Val Loss: 12.2675
[2026-02-25 00:40:06] [INFO] [DEF]: Val Acc: 0.9367
[2026-02-25 00:40:10] [INFO] [DEF]: Epoch [34/100]
[2026-02-25 00:40:10] [INFO] [DEF]: Train Loss: 13.4301
[2026-02-25 00:40:10] [INFO] [DEF]: Train Acc: 0.9611
[2026-02-25 00:40:10] [INFO] [DEF]: Val Loss: 7.1396
[2026-02-25 00:40:10] [INFO] [DEF]: Val Acc: 0.9357
[2026-02-25 00:40:15] [INFO] [DEF]: Epoch [35/100]
[2026-02-25 00:40:15] [INFO] [DEF]: Train Loss: 14.3392
[2026-02-25 00:40:15] [INFO] [DEF]: Train Acc: 0.9592
[2026-02-25 00:40:15] [INFO] [DEF]: Val Loss: 16.9907
[2026-02-25 00:40:15] [INFO] [DEF]: Val Acc: 0.8543
[2026-02-25 00:40:19] [INFO] [DEF]: Epoch [36/100]
[2026-02-25 00:40:19] [INFO] [DEF]: Train Loss: 12.9099
[2026-02-25 00:40:19] [INFO] [DEF]: Train Acc: 0.9636
[2026-02-25 00:40:19] [INFO] [DEF]: Val Loss: 13.0665
[2026-02-25 00:40:19] [INFO] [DEF]: Val Acc: 0.9307
[2026-02-25 00:40:23] [INFO] [DEF]: Epoch [37/100]
[2026-02-25 00:40:23] [INFO] [DEF]: Train Loss: 10.1592
[2026-02-25 00:40:23] [INFO] [DEF]: Train Acc: 0.9703
[2026-02-25 00:40:23] [INFO] [DEF]: Val Loss: 32.8438
[2026-02-25 00:40:23] [INFO] [DEF]: Val Acc: 0.7558
[2026-02-25 00:40:28] [INFO] [DEF]: Epoch [38/100]
[2026-02-25 00:40:28] [INFO] [DEF]: Train Loss: 10.4643
[2026-02-25 00:40:28] [INFO] [DEF]: Train Acc: 0.9711
[2026-02-25 00:40:28] [INFO] [DEF]: Val Loss: 9.7271
[2026-02-25 00:40:28] [INFO] [DEF]: Val Acc: 0.8874
[2026-02-25 00:40:32] [INFO] [DEF]: Epoch [39/100]
[2026-02-25 00:40:32] [INFO] [DEF]: Train Loss: 11.9481
[2026-02-25 00:40:32] [INFO] [DEF]: Train Acc: 0.9650
[2026-02-25 00:40:32] [INFO] [DEF]: Val Loss: 17.6461
[2026-02-25 00:40:32] [INFO] [DEF]: Val Acc: 0.9307
[2026-02-25 00:40:36] [INFO] [DEF]: Epoch [40/100]
[2026-02-25 00:40:36] [INFO] [DEF]: Train Loss: 13.0796
[2026-02-25 00:40:36] [INFO] [DEF]: Train Acc: 0.9629
[2026-02-25 00:40:36] [INFO] [DEF]: Val Loss: 62.6875
[2026-02-25 00:40:36] [INFO] [DEF]: Val Acc: 0.6322
[2026-02-25 00:40:40] [INFO] [DEF]: Epoch [41/100]
[2026-02-25 00:40:40] [INFO] [DEF]: Train Loss: 12.2307
[2026-02-25 00:40:40] [INFO] [DEF]: Train Acc: 0.9641
[2026-02-25 00:40:40] [INFO] [DEF]: Val Loss: 10.6915
[2026-02-25 00:40:40] [INFO] [DEF]: Val Acc: 0.8985
[2026-02-25 00:40:45] [INFO] [DEF]: Epoch [42/100]
[2026-02-25 00:40:45] [INFO] [DEF]: Train Loss: 11.0215
[2026-02-25 00:40:45] [INFO] [DEF]: Train Acc: 0.9683
[2026-02-25 00:40:45] [INFO] [DEF]: Val Loss: 9.4897
[2026-02-25 00:40:45] [INFO] [DEF]: Val Acc: 0.9307
[2026-02-25 00:40:49] [INFO] [DEF]: Epoch [43/100]
[2026-02-25 00:40:49] [INFO] [DEF]: Train Loss: 10.7750
[2026-02-25 00:40:49] [INFO] [DEF]: Train Acc: 0.9694
[2026-02-25 00:40:49] [INFO] [DEF]: Val Loss: 19.2575
[2026-02-25 00:40:49] [INFO] [DEF]: Val Acc: 0.8653
[2026-02-25 00:40:53] [INFO] [DEF]: Epoch [44/100]
[2026-02-25 00:40:53] [INFO] [DEF]: Train Loss: 10.7460
[2026-02-25 00:40:53] [INFO] [DEF]: Train Acc: 0.9684
[2026-02-25 00:40:53] [INFO] [DEF]: Val Loss: 26.9914
[2026-02-25 00:40:53] [INFO] [DEF]: Val Acc: 0.8945
[2026-02-25 00:40:58] [INFO] [DEF]: Epoch [45/100]
[2026-02-25 00:40:58] [INFO] [DEF]: Train Loss: 10.4831
[2026-02-25 00:40:58] [INFO] [DEF]: Train Acc: 0.9680
[2026-02-25 00:40:58] [INFO] [DEF]: Val Loss: 23.7985
[2026-02-25 00:40:58] [INFO] [DEF]: Val Acc: 0.8332
[2026-02-25 00:41:02] [INFO] [DEF]: Epoch [46/100]
[2026-02-25 00:41:02] [INFO] [DEF]: Train Loss: 11.2220
[2026-02-25 00:41:02] [INFO] [DEF]: Train Acc: 0.9660
[2026-02-25 00:41:02] [INFO] [DEF]: Val Loss: 22.9608
[2026-02-25 00:41:02] [INFO] [DEF]: Val Acc: 0.9055
[2026-02-25 00:41:06] [INFO] [DEF]: Epoch [47/100]
[2026-02-25 00:41:06] [INFO] [DEF]: Train Loss: 11.4011
[2026-02-25 00:41:06] [INFO] [DEF]: Train Acc: 0.9678
[2026-02-25 00:41:06] [INFO] [DEF]: Val Loss: 36.2135
[2026-02-25 00:41:06] [INFO] [DEF]: Val Acc: 0.7819
[2026-02-25 00:41:10] [INFO] [DEF]: Epoch [48/100]
[2026-02-25 00:41:10] [INFO] [DEF]: Train Loss: 10.3354
[2026-02-25 00:41:10] [INFO] [DEF]: Train Acc: 0.9709
[2026-02-25 00:41:10] [INFO] [DEF]: Val Loss: 29.8997
[2026-02-25 00:41:10] [INFO] [DEF]: Val Acc: 0.7236
[2026-02-25 00:41:14] [INFO] [DEF]: Epoch [49/100]
[2026-02-25 00:41:14] [INFO] [DEF]: Train Loss: 8.1665
[2026-02-25 00:41:14] [INFO] [DEF]: Train Acc: 0.9755
[2026-02-25 00:41:14] [INFO] [DEF]: Val Loss: 49.8861
[2026-02-25 00:41:14] [INFO] [DEF]: Val Acc: 0.7628
[2026-02-25 00:41:18] [INFO] [DEF]: Epoch [50/100]
[2026-02-25 00:41:18] [INFO] [DEF]: Train Loss: 7.6672
[2026-02-25 00:41:18] [INFO] [DEF]: Train Acc: 0.9787
[2026-02-25 00:41:18] [INFO] [DEF]: Val Loss: 9.4416
[2026-02-25 00:41:18] [INFO] [DEF]: Val Acc: 0.9417
[2026-02-25 00:41:22] [INFO] [DEF]: Epoch [51/100]
[2026-02-25 00:41:22] [INFO] [DEF]: Train Loss: 10.8505
[2026-02-25 00:41:22] [INFO] [DEF]: Train Acc: 0.9699
[2026-02-25 00:41:22] [INFO] [DEF]: Val Loss: 19.9748
[2026-02-25 00:41:22] [INFO] [DEF]: Val Acc: 0.8804
[2026-02-25 00:41:25] [INFO] [DEF]: Epoch [52/100]
[2026-02-25 00:41:25] [INFO] [DEF]: Train Loss: 8.3552
[2026-02-25 00:41:25] [INFO] [DEF]: Train Acc: 0.9766
[2026-02-25 00:41:25] [INFO] [DEF]: Val Loss: 9.2407
[2026-02-25 00:41:25] [INFO] [DEF]: Val Acc: 0.9538
[2026-02-25 00:41:30] [INFO] [DEF]: Epoch [53/100]
[2026-02-25 00:41:30] [INFO] [DEF]: Train Loss: 6.9968
[2026-02-25 00:41:30] [INFO] [DEF]: Train Acc: 0.9809
[2026-02-25 00:41:30] [INFO] [DEF]: Val Loss: 16.6681
[2026-02-25 00:41:30] [INFO] [DEF]: Val Acc: 0.8342
[2026-02-25 00:41:34] [INFO] [DEF]: Epoch [54/100]
[2026-02-25 00:41:34] [INFO] [DEF]: Train Loss: 7.4763
[2026-02-25 00:41:34] [INFO] [DEF]: Train Acc: 0.9778
[2026-02-25 00:41:34] [INFO] [DEF]: Val Loss: 7.6180
[2026-02-25 00:41:34] [INFO] [DEF]: Val Acc: 0.9307
[2026-02-25 00:41:38] [INFO] [DEF]: Epoch [55/100]
[2026-02-25 00:41:38] [INFO] [DEF]: Train Loss: 6.5296
[2026-02-25 00:41:38] [INFO] [DEF]: Train Acc: 0.9831
[2026-02-25 00:41:38] [INFO] [DEF]: Val Loss: 17.2817
[2026-02-25 00:41:38] [INFO] [DEF]: Val Acc: 0.8181
[2026-02-25 00:41:42] [INFO] [DEF]: Epoch [56/100]
[2026-02-25 00:41:42] [INFO] [DEF]: Train Loss: 7.2056
[2026-02-25 00:41:42] [INFO] [DEF]: Train Acc: 0.9801
[2026-02-25 00:41:42] [INFO] [DEF]: Val Loss: 41.5624
[2026-02-25 00:41:42] [INFO] [DEF]: Val Acc: 0.7206
[2026-02-25 00:41:46] [INFO] [DEF]: Epoch [57/100]
[2026-02-25 00:41:46] [INFO] [DEF]: Train Loss: 8.5829
[2026-02-25 00:41:46] [INFO] [DEF]: Train Acc: 0.9736
[2026-02-25 00:41:46] [INFO] [DEF]: Val Loss: 10.9881
[2026-02-25 00:41:46] [INFO] [DEF]: Val Acc: 0.8834
[2026-02-25 00:41:50] [INFO] [DEF]: Epoch [58/100]
[2026-02-25 00:41:50] [INFO] [DEF]: Train Loss: 9.1595
[2026-02-25 00:41:50] [INFO] [DEF]: Train Acc: 0.9766
[2026-02-25 00:41:50] [INFO] [DEF]: Val Loss: 14.6514
[2026-02-25 00:41:50] [INFO] [DEF]: Val Acc: 0.7869
[2026-02-25 00:41:54] [INFO] [DEF]: Epoch [59/100]
[2026-02-25 00:41:54] [INFO] [DEF]: Train Loss: 8.5885
[2026-02-25 00:41:54] [INFO] [DEF]: Train Acc: 0.9755
[2026-02-25 00:41:54] [INFO] [DEF]: Val Loss: 12.2915
[2026-02-25 00:41:54] [INFO] [DEF]: Val Acc: 0.8955
[2026-02-25 00:41:58] [INFO] [DEF]: Epoch [60/100]
[2026-02-25 00:41:58] [INFO] [DEF]: Train Loss: 8.8960
[2026-02-25 00:41:58] [INFO] [DEF]: Train Acc: 0.9741
[2026-02-25 00:41:58] [INFO] [DEF]: Val Loss: 54.3086
[2026-02-25 00:41:58] [INFO] [DEF]: Val Acc: 0.6181
[2026-02-25 00:42:03] [INFO] [DEF]: Epoch [61/100]
[2026-02-25 00:42:03] [INFO] [DEF]: Train Loss: 7.0054
[2026-02-25 00:42:03] [INFO] [DEF]: Train Acc: 0.9817
[2026-02-25 00:42:03] [INFO] [DEF]: Val Loss: 44.1522
[2026-02-25 00:42:03] [INFO] [DEF]: Val Acc: 0.7226
[2026-02-25 00:42:08] [INFO] [DEF]: Epoch [62/100]
[2026-02-25 00:42:08] [INFO] [DEF]: Train Loss: 6.4708
[2026-02-25 00:42:08] [INFO] [DEF]: Train Acc: 0.9807
[2026-02-25 00:42:08] [INFO] [DEF]: Val Loss: 68.9130
[2026-02-25 00:42:08] [INFO] [DEF]: Val Acc: 0.7136
[2026-02-25 00:42:12] [INFO] [DEF]: Epoch [63/100]
[2026-02-25 00:42:12] [INFO] [DEF]: Train Loss: 6.0554
[2026-02-25 00:42:12] [INFO] [DEF]: Train Acc: 0.9839
[2026-02-25 00:42:12] [INFO] [DEF]: Val Loss: 23.6294
[2026-02-25 00:42:12] [INFO] [DEF]: Val Acc: 0.8774
[2026-02-25 00:42:17] [INFO] [DEF]: Epoch [64/100]
[2026-02-25 00:42:17] [INFO] [DEF]: Train Loss: 7.1404
[2026-02-25 00:42:17] [INFO] [DEF]: Train Acc: 0.9796
[2026-02-25 00:42:17] [INFO] [DEF]: Val Loss: 24.0303
[2026-02-25 00:42:17] [INFO] [DEF]: Val Acc: 0.8553
[2026-02-25 00:42:22] [INFO] [DEF]: Epoch [65/100]
[2026-02-25 00:42:22] [INFO] [DEF]: Train Loss: 7.9358
[2026-02-25 00:42:22] [INFO] [DEF]: Train Acc: 0.9789
[2026-02-25 00:42:22] [INFO] [DEF]: Val Loss: 29.4465
[2026-02-25 00:42:22] [INFO] [DEF]: Val Acc: 0.8864
[2026-02-25 00:42:26] [INFO] [DEF]: Epoch [66/100]
[2026-02-25 00:42:26] [INFO] [DEF]: Train Loss: 6.6195
[2026-02-25 00:42:26] [INFO] [DEF]: Train Acc: 0.9814
[2026-02-25 00:42:26] [INFO] [DEF]: Val Loss: 10.6372
[2026-02-25 00:42:26] [INFO] [DEF]: Val Acc: 0.9146
[2026-02-25 00:42:31] [INFO] [DEF]: Epoch [67/100]
[2026-02-25 00:42:31] [INFO] [DEF]: Train Loss: 6.6188
[2026-02-25 00:42:31] [INFO] [DEF]: Train Acc: 0.9788
[2026-02-25 00:42:31] [INFO] [DEF]: Val Loss: 7.6547
[2026-02-25 00:42:31] [INFO] [DEF]: Val Acc: 0.9397
[2026-02-25 00:42:36] [INFO] [DEF]: Epoch [68/100]
[2026-02-25 00:42:36] [INFO] [DEF]: Train Loss: 5.5327
[2026-02-25 00:42:36] [INFO] [DEF]: Train Acc: 0.9828
[2026-02-25 00:42:36] [INFO] [DEF]: Val Loss: 46.1845
[2026-02-25 00:42:36] [INFO] [DEF]: Val Acc: 0.8774
[2026-02-25 00:42:41] [INFO] [DEF]: Epoch [69/100]
[2026-02-25 00:42:41] [INFO] [DEF]: Train Loss: 6.2074
[2026-02-25 00:42:41] [INFO] [DEF]: Train Acc: 0.9822
[2026-02-25 00:42:41] [INFO] [DEF]: Val Loss: 87.3894
[2026-02-25 00:42:41] [INFO] [DEF]: Val Acc: 0.7980
[2026-02-25 00:42:45] [INFO] [DEF]: Epoch [70/100]
[2026-02-25 00:42:45] [INFO] [DEF]: Train Loss: 6.6182
[2026-02-25 00:42:45] [INFO] [DEF]: Train Acc: 0.9822
[2026-02-25 00:42:45] [INFO] [DEF]: Val Loss: 30.3682
[2026-02-25 00:42:45] [INFO] [DEF]: Val Acc: 0.8442
[2026-02-25 00:42:50] [INFO] [DEF]: Epoch [71/100]
[2026-02-25 00:42:50] [INFO] [DEF]: Train Loss: 7.5328
[2026-02-25 00:42:50] [INFO] [DEF]: Train Acc: 0.9793

C:\Users\91748\AppData\Local\Temp\ipykernel_1436\1181449524.py:130: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(

[2026-02-25 00:44:57] [INFO] [DEF]: Test Accuracy: 0.9559748427672956
[2026-02-25 00:44:57] [INFO] [FIN]: Execution Complete.
[2026-02-25 00:44:57] [INFO] [MET]: END Session 11

In [83]:
json_inter.save_config_to_json(CONFIG, "experiments_metadata")

In [84]:
json_inter.load_config_as_dataframe("experiments_metadata")

,run_id,dataset_id,batch_size,epochs,learning_rate,use_class_weights,model_name,dataset_path,model_save_path,num_classes,timestamp,size
0,001,009,64,100,0.001,True,cnn001,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...,4,2026-02-25 00:30:22,0.0 MB
1,002,011,64,100,0.001,True,cnn001,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...,4,2026-02-25 00:35:57,0.0 MB
2,003,011,64,100,0.001,True,cnn001,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...,4,2026-02-25 00:35:57,0.0 MB
3,004,012,64,100,0.001,True,cnn001,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...,4,2026-02-25 00:44:57,0.0 MB
4,005,012,64,100,0.001,True,cnn001,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...,D:\Repos\FPGA_Radar_Microdoppler_Classificatio...,4,2026-02-25 00:45:01,0.0 MB